-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 16:21:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`оброзовательные материалы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`оброзовательные материалы` (
                                                                  `тема материала` ENUM('a', 'b') NOT NULL,
    `уровень` ENUM('school', 'high school', 'student') NOT NULL,
    PRIMARY KEY (`тема материала`, `уровень`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Пользователь`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Пользователь` (
                                                     `id` INT NOT NULL,
                                                     `Имя` TINYTEXT NOT NULL,
                                                     `Фамилия` TINYTEXT NOT NULL,
                                                     `Отчество` TINYTEXT NOT NULL,
                                                     `Должность/Уровень` ENUM('admin', 'moderator', 'teacher', 'school', 'high school', 'student') NOT NULL,
    `оброзовательные материалы_оброзовательные материалыcol` INT NOT NULL,
    `оброзовательные материалы_тема материала` ENUM('a', 'b') NOT NULL,
    `оброзовательные материалы_уровень` ENUM('school', 'high school', 'student') NOT NULL,
    PRIMARY KEY (`id`, `оброзовательные материалы_оброзовательные материалыcol`, `оброзовательные материалы_тема материала`, `оброзовательные материалы_уровень`),
    INDEX `fk_Пользователь_оброзовательные _idx` (`оброзовательные материалы_тема материала` ASC, `оброзовательные материалы_уровень` ASC) VISIBLE,
    CONSTRAINT `fk_Пользователь_оброзовательные м1`
    FOREIGN KEY (`оброзовательные материалы_тема материала` , `оброзовательные материалы_уровень`)
    REFERENCES `mydb`.`оброзовательные материалы` (`тема материала` , `уровень`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вопрос с вариантами ответа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вопрос с вариантами ответа` (
                                                                   `id` INT NOT NULL,
                                                                   `id правильного варианта` INT NOT NULL,
                                                                   `текст вопроса` TINYTEXT NOT NULL,
                                                                   PRIMARY KEY (`id`, `id правильного варианта`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вариант ответа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вариант ответа` (
                                                       `id` INT NOT NULL,
                                                       `текст ответа` TINYTEXT NOT NULL,
                                                       PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вопрос с вариантами ответа_has_вариант ответа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вопрос с вариантами ответа_has_вариант ответа` (
                                                                                      `вопрос с вариантами ответа_id` INT NOT NULL,
                                                                                      `вопрос с вариантами ответа_id правильного варианта` INT NOT NULL,
                                                                                      `вариант ответа_id` INT NOT NULL,
                                                                                      PRIMARY KEY (`вопрос с вариантами ответа_id`, `вопрос с вариантами ответа_id правильного варианта`, `вариант ответа_id`),
    INDEX `fk_вопрос с вариантами ответа_has_в_idx1` (`вопрос с вариантами ответа_id` ASC, `вопрос с вариантами ответа_id правильного варианта` ASC) VISIBLE,
    INDEX `fk_вопрос с вариантами ответа_has_в_idx` (`вариант ответа_id` ASC) VISIBLE,
    CONSTRAINT `fk_вопрос с вариантами ответа_has_ва`
    FOREIGN KEY (`вопрос с вариантами ответа_id` , `вопрос с вариантами ответа_id правильного варианта`)
    REFERENCES `mydb`.`вопрос с вариантами ответа` (`id` , `id правильного варианта`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_вопрос с вариантами ответа_has_ва1`
    FOREIGN KEY (`вариант ответа_id`)
    REFERENCES `mydb`.`вариант ответа` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вопрос с несколькими вариантами ответа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вопрос с несколькими вариантами ответа` (
                                                                               `id` INT NOT NULL,
                                                                               `id правильного ответа` INT NOT NULL,
                                                                               `текст вопроса` TINYTEXT NULL,
                                                                               PRIMARY KEY (`id`, `id правильного ответа`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вопрос с несколькими вариантами ответа_has_вариант ответа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вопрос с несколькими вариантами ответа_has_вариант ответа` (
                                                                                                  `вопрос с несколькими вариантами ответа_id` INT NOT NULL,
                                                                                                  `вопрос с несколькими вариантами ответа_id правильного ответа 4` INT NOT NULL,
                                                                                                  `вариант ответа_id` INT NOT NULL,
                                                                                                  PRIMARY KEY (`вопрос с несколькими вариантами ответа_id`, `вопрос с несколькими вариантами ответа_id правильного ответа 4`, `вариант ответа_id`),
    INDEX `fk_table2_has_table11_table21_idx` (`вопрос с несколькими вариантами ответа_id` ASC, `вопрос с несколькими вариантами ответа_id правильного ответа 4` ASC) VISIBLE,
    INDEX `fk_table2_has_table11_вариант ответа1_idx` (`вариант ответа_id` ASC) VISIBLE,
    CONSTRAINT `fk_table2_has_table11_table21`
    FOREIGN KEY (`вопрос с несколькими вариантами ответа_id` , `вопрос с несколькими вариантами ответа_id правильного ответа 4`)
    REFERENCES `mydb`.`вопрос с несколькими вариантами ответа` (`id` , `id правильного ответа`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_table2_has_table11_вариант ответа1`
    FOREIGN KEY (`вариант ответа_id`)
    REFERENCES `mydb`.`вариант ответа` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вопрос с письменным ответом`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вопрос с письменным ответом` (
                                                                    `idвопрос с письменным ответом` INT NOT NULL,
                                                                    `текст вопроса` TINYTEXT NOT NULL,
                                                                    `правильный ответ` TINYTEXT NOT NULL,
                                                                    PRIMARY KEY (`idвопрос с письменным ответом`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`тест`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`тест` (
                                             `id` INT NOT NULL,
                                             `уровень` ENUM('school', 'high school', 'student') NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вопрос с вариантами ответа_has_тест`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вопрос с вариантами ответа_has_тест` (
                                                                            `вопрос с вариантами ответа_id` INT NOT NULL,
                                                                            `вопрос с вариантами ответа_id правильного варианта` INT NOT NULL,
                                                                            `тест_id` INT NOT NULL,
                                                                            PRIMARY KEY (`вопрос с вариантами ответа_id`, `вопрос с вариантами ответа_id правильного варианта`, `тест_id`),
    INDEX `fk_вопрос с вариантами ответа_has_т_idx` (`тест_id` ASC) VISIBLE,
    INDEX `fk_вопрос с вариантами ответа_has_т_idx1` (`вопрос с вариантами ответа_id` ASC, `вопрос с вариантами ответа_id правильного варианта` ASC) VISIBLE,
    CONSTRAINT `fk_вопрос с вариантами ответа_has_те1`
    FOREIGN KEY (`вопрос с вариантами ответа_id` , `вопрос с вариантами ответа_id правильного варианта`)
    REFERENCES `mydb`.`вопрос с вариантами ответа` (`id` , `id правильного варианта`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_вопрос с вариантами ответа_has_те2`
    FOREIGN KEY (`тест_id`)
    REFERENCES `mydb`.`тест` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`вопрос с письменным ответом_has_тест`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`вопрос с письменным ответом_has_тест` (
                                                                             `вопрос с письменным ответом_idвопрос с письменным ответом` INT NOT NULL,
                                                                             `тест_id` INT NOT NULL,
                                                                             PRIMARY KEY (`вопрос с письменным ответом_idвопрос с письменным ответом`, `тест_id`),
    INDEX `fk_вопрос с письменным ответом_has__idx` (`тест_id` ASC) VISIBLE,
    INDEX `fk_вопрос с письменным ответом_has__idx1` (`вопрос с письменным ответом_idвопрос с письменным ответом` ASC) VISIBLE,
    CONSTRAINT `fk_вопрос с письменным ответом_has_т1`
    FOREIGN KEY (`вопрос с письменным ответом_idвопрос с письменным ответом`)
    REFERENCES `mydb`.`вопрос с письменным ответом` (`idвопрос с письменным ответом`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_вопрос с письменным ответом_has_т2`
    FOREIGN KEY (`тест_id`)
    REFERENCES `mydb`.`тест` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`тест_has_вопрос с несколькими вариантами ответа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`тест_has_вопрос с несколькими вариантами ответа` (
                                                                                        `тест_id` INT NOT NULL,
                                                                                        `вопрос с несколькими вариантами ответа_idtable2` INT NOT NULL,
                                                                                        `вопрос с несколькими вариантами ответа_id правильного ответа 4` INT NOT NULL,
                                                                                        PRIMARY KEY (`тест_id`, `вопрос с несколькими вариантами ответа_idtable2`, `вопрос с несколькими вариантами ответа_id правильного ответа 4`),
    INDEX `fk_тест_has_вопрос с несколькими ва_idx` (`вопрос с несколькими вариантами ответа_idtable2` ASC, `вопрос с несколькими вариантами ответа_id правильного ответа 4` ASC) VISIBLE,
    INDEX `fk_тест_has_вопрос с несколькими ва_idx1` (`тест_id` ASC) VISIBLE,
    CONSTRAINT `fk_тест_has_вопрос с несколькими вар1`
    FOREIGN KEY (`тест_id`)
    REFERENCES `mydb`.`тест` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_тест_has_вопрос с несколькими вар2`
    FOREIGN KEY (`вопрос с несколькими вариантами ответа_idtable2` , `вопрос с несколькими вариантами ответа_id правильного ответа 4`)
    REFERENCES `mydb`.`вопрос с несколькими вариантами ответа` (`id` , `id правильного ответа`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Пользователь_has_тест`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Пользователь_has_тест` (
                                                              `Пользователь_id` INT NOT NULL,
                                                              `Пользователь_оброзовательные материалы_оброзовательные материалыcol` INT NOT NULL,
                                                              `тест_id` INT NOT NULL,
                                                              PRIMARY KEY (`Пользователь_id`, `Пользователь_оброзовательные материалы_оброзовательные материалыcol`, `тест_id`),
    INDEX `fk_Пользователь_has_тест_тест1_idx` (`тест_id` ASC) VISIBLE,
    INDEX `fk_Пользователь_has_тест_Пользоват_idx` (`Пользователь_id` ASC, `Пользователь_оброзовательные материалы_оброзовательные материалыcol` ASC) VISIBLE,
    CONSTRAINT `fk_Пользователь_has_тест_Пользовате1`
    FOREIGN KEY (`Пользователь_id` , `Пользователь_оброзовательные материалы_оброзовательные материалыcol`)
    REFERENCES `mydb`.`Пользователь` (`id` , `оброзовательные материалы_оброзовательные материалыcol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Пользователь_has_тест_тест1`
    FOREIGN KEY (`тест_id`)
    REFERENCES `mydb`.`тест` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`текст материала`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`текст материала` (
                                                        `id` INT NOT NULL,
                                                        `текст материалаcol` MEDIUMTEXT NOT NULL,
                                                        `тема` ENUM('a', 'b') NOT NULL,
    `оброзовательные материалы_тема материала` ENUM('a', 'b') NOT NULL,
    PRIMARY KEY (`id`, `тема`, `оброзовательные материалы_тема материала`),
    INDEX `fk_текст материала_оброзовательн_idx` (`оброзовательные материалы_тема материала` ASC) VISIBLE,
    CONSTRAINT `fk_текст материала_оброзовательны1`
    FOREIGN KEY (`оброзовательные материалы_тема материала`)
    REFERENCES `mydb`.`оброзовательные материалы` (`тема материала`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
